include base.mk

install:
	$(call link-user-file,xmodmaprc,.xmodmaprc)
	$(call link-user-file,Xdefaults,.Xdefaults)

uninstall:
	$(call unlink-user-file,.xmodmaprc)
	$(call unlink-user-file,.Xdefaults)
