include base.mk

install:
	$(call link-user-file,config,.newsbeuter/config)
	$(call link-user-file,urls,.newsbeuter/urls)

uninstall:
	$(call unlink-user-file,.newsbeuter/config)
	$(call unlink-user-file,.newsbeuter/urls)
