if has("gui_macvim")
  macmenu File.New\ Window                    key=<nop>
  macmenu File.New\ Tab                       key=<nop>
  macmenu File.Open\.\.\.                     key=<nop>
  macmenu File.Open\ Tab\.\.\.                key=<nop>
  macmenu File.Close\ Window                  key=<nop>
  macmenu File.Close                          key=<nop>
  macmenu File.Save                           key=<nop>
  macmenu File.Save\ All                      key=<nop>
  macmenu File.Save\ As\.\.\.                 key=<nop>
  macmenu File.Print                          key=<nop>

  macmenu Edit.Undo                           key=<nop>
  macmenu Edit.Redo                           key=<nop>
  macmenu Edit.Cut                            key=<nop>
  macmenu Edit.Copy                           key=<nop>
  macmenu Edit.Paste                          key=<nop>
  macmenu Edit.Select\ All                    key=<nop>
  macmenu Edit.Find.Find\.\.\.                key=<nop>
  macmenu Edit.Find.Find\ Next                key=<nop>
  macmenu Edit.Find.Find\ Previous            key=<nop>
  macmenu Edit.Find.Use\ Selection\ for\ Find key=<nop>
  macmenu Edit.Font.Bigger                    key=<nop>
  macmenu Edit.Font.Smaller                   key=<nop>

  macmenu Tools.Spelling.Suggest\ Corrections key=<nop>
  macmenu Tools.Make                          key=<nop>
  macmenu Tools.List\ Errors                  key=<nop>
  macmenu Tools.Next\ Error                   key=<nop>
  macmenu Tools.Previous\ Error               key=<nop>
  macmenu Tools.Older\ List                   key=<nop>
  macmenu Tools.Newer\ List                   key=<nop>

  macmenu Window.Select\ Next\ Tab            key=<nop>
  macmenu Window.Select\ Previous\ Tab        key=<nop>

  macmenu Help.MacVim\ Help                   key=<nop>
endif
