#!/bin/sh

set -e
set -u

REMOTE="$(git remote get-url origin 2>/dev/null || true)"
if [[ $REMOTE =~ "balena" ]]
then
  echo "Using balena email..."
  git config user.email "juan@balena.io"
fi

git commit -v --signoff $*
