#!/bin/sh

# Recursively search & replace in the current directory

set -u
set -e

if [ $# -lt 2 ]
then
  echo "Usage: $0 <pattern> <replacement>" >&2
  exit 1
fi

pattern=$1
replacement=$2

/usr/bin/find . -type f -exec sed -i '' "s/$pattern/$replacement/g" {} +
