#!/bin/sh

# Recursively search & replace in the current directory

set -u
set -e

if [ $# -lt 2 ]
then
  echo "Usage: $0 <pattern> <replacement>" >&2
  exit 1
fi

pattern=$1
replacement=$2

/usr/bin/find . -type f -print0 | while IFS= read -r -d '' file
do
  # To gracefully skip binary files
  TYPE="$(file -b --mime-type "$file")"
  if echo "$TYPE" | grep -q "^text/"
  then
    echo "Processing $file" 1>&2
    sed -i '' "s/$pattern/$replacement/g" "$file"
  else
    echo "Ignoring $file" 1>&2
    continue
  fi
done
